# Generated by Django 4.0.4 on 2022-04-25 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='status',
            field=models.CharField(blank=True, choices=[('Owned', 'Owned'), ('Dreaming', 'Dreaming')], max_length=10),
        ),
    ]
