# Generated by Django 4.0.4 on 2022-04-26 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_car_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='status',
        ),
    ]
