# Generated by Django 4.0.4 on 2022-04-27 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_passenger_car_passengers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='passengers',
        ),
    ]
