# Generated by Django 4.0.4 on 2022-04-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_car_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(blank=True, choices=[('Dreaming', 'Dreaming')], max_length=10),
        ),
    ]
