# Generated by Django 4.0.4 on 2022-04-26 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_car_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(blank=True, choices=[('owned', 'Owned'), ('dreaming', 'Dreaming'), ('yesButNo', 'dislike it but it cool')], max_length=10),
        ),
    ]
