# Generated by Django 4.0.4 on 2022-04-27 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_car_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(blank=True, choices=[('Owned', 'Owned'), ('Dreaming', 'Dreaming'), ('Dislike it but it cool', 'Dislike it but it cool')], max_length=100),
        ),
    ]
