# Generated by Django 4.0.4 on 2022-04-27 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_service_options_alter_service_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='status',
        ),
    ]
